# Linear Regression in Python using Numpy
---

### Exploring the use of Numpy matrices & Scikit learn

In [1]:
import numpy as np

In [12]:
a = np.matrix('1 2; 3 4')
print a
print a.T # transpose of matrix a

b = np.matrix('1;2')
print a*b

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[ 5]
 [11]]


In [24]:
def gradientDescent(X, y, theta, alpha, num_iters):
    dx = ((X*theta-y).T * X).T
    theta = theta - (alpha * dx)
    return theta

def computeCost(X,y,theta):
    J = (X*theta-y).T * (X*theta-y) / (2*m)
    return J

def featureNormalize(X):
    X_norm = X.copy;
    mu = X.std(1)
    sigma = X.mean(1)
    
    for i in X.shape:
        X_norm[:,i] = (X[:,i]-mu[i])/sigma[i]
        
    return X_norm, mu, sigma